name: Send Training Poll
on:

  schedule:
    - cron: '0 10 * * 1'  # Понедельник 13:00 МСК
    - cron: '0 10 * * 3'  # Среда 13:00 МСК
    - cron: '0 10 * * 5'  # Пятница 13:00 МСК
  workflow_dispatch:

jobs:
  send-poll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install python-telegram-bot
      - run: python poll.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
